# workshop preparation


## Does Reticulate work with Aaron's package?

2 issues:
- R does not have something equivalent to the python pandas time series
- R functions do not support multiple outputs (must be in a list)

Solutions:
- a couple lines of python code to convert from data frame to time series in the background
- capture python code output as R list

In [14]:
library(reticulate)

In [15]:
Sys.which('python')

                 python
"/opt/conda/bin/python"

# Option 1: call python script from R
This will capture output as a R list. Access objects through `XX$XX`

In [4]:
result = py_run_file("EDA-PhosPerch.py")

In [5]:
result$df_perch

1943-01-01 1944-01-01 1945-01-01 1946-01-01 1947-01-01 1948-01-01 1949-01-01
     90.22      58.59      59.25      62.72      19.90      29.42       6.20
1950-01-01 1951-01-01 1952-01-01 1953-01-01 1954-01-01 1955-01-01 1959-01-01
      5.82      17.64       7.84      13.10       9.25       6.26      14.12
1960-01-01 1961-01-01 1962-01-01 1963-01-01 1964-01-01 1965-01-01 1966-01-01
     53.63      47.07      99.03      89.37      53.60      28.87      28.23
1967-01-01 1968-01-01 1969-01-01 1970-01-01 1971-01-01 1973-01-01 1974-01-01
     14.27      19.23      24.67      45.00      38.37      34.50      30.47
1975-01-01 1976-01-01 1977-01-01 1978-01-01 1979-01-01 1980-01-01 1981-01-01
     32.47      37.23       3.90       9.60       5.60      26.40       8.87
1982-01-01 1983-01-01 1984-01-01 1985-01-01 1986-01-01 1987-01-01 1988-01-01
     38.70      13.47      21.13       2.73      25.60      19.77      20.63
1989-01-01 1990-01-01 1993-01-01 1994-01-01 1995-01-01 1996-01-01 1997-01-01
     37.73      29.10      33.27      16.33      19.30      79.67      55.17
1998-01-01 1999-01-01 2000-01-01 2001-01-01 2002-01-01 2003-01-01 2004-01-01
     22.30      25.13      13.80      43.30      27.83       4.63      17.36
2005-01-01 2006-01-01 2007-01-01 2008-01-01 2009-01-01 2010-01-01 2011-01-01
      3.77      23.47      72.23      45.37      41.33      30.07      28.30
2012-01-01
     16.17

# Option 2: pass R data frame to python 
This will capture output as a R list. Access objects through `XX$XX` or `XX[[x]]`

In [6]:
source_python("cpt/dp.py")
source_python("cpt/data.py")
source_python("cpt/cost.py")
source_python("cpt/functions.py")
source_python("cpt/penalty.py")
source_python("cpt/df_to_ts.py")

In [7]:
#from cpt.dp import CPT_DSF, DP_allpenfast
#from cpt.cost import NORMAL_MEANVAR
#from cpt.penalty import PENFUN_BIC

df_perch = data.frame(DATETIME = 1:10, VALUE=1:10)
df_phos = data.frame(DATETIME = 1:100, VALUE=1:100)
ts = list(df_perch, df_phos)
names = c('Perch', 'Phos')
N = length(ts)
costfun = list()
for(i in 1:N) {costfun[[i]] <- NORMAL_MEANVAR}
penfun = PENFUN_BIC
minseglen = rep(2,N)

In [8]:

#hat_cpts, hat_cpts_uni, hat_lik, hat_lik_uni =
a = CPT_DSF(list(DF_TO_TS(df_perch),DF_TO_TS(df_phos)), costfun, penfun, minseglen, DP_allpenfast) # unfortnuately R returns multi-argument outputs as lists
names(a) <- c('hat_cpts','hat_cpts_uni','hat_lik','hat_lik_uni') # assign name for items in list

In [9]:
a$hat_cpts

[1] "99" "4"

In [10]:
a[[1]]

[1] "99" "4"

In [13]:
print( a )

$hat_cpts
[1] "99" "4"

$hat_cpts_uni
$hat_cpts_uni[[1]]
[1] "10" "10"

$hat_cpts_uni[[2]]
[1] "100" "100"


$hat_lik
  [1] -20.723266   0.000000   0.000000   0.000000   0.000000   0.000000
  [7]   0.000000   0.000000   0.000000   0.000000   0.000000   0.000000
 [13]   0.000000   5.806331   5.806331   5.806331   5.806331   5.806331
 [19]   5.806331   5.806331   5.806331   5.806331   5.806331   5.806331
 [25]  14.594472  14.594472  14.594472  14.594472  14.594472  14.594472
 [31]  14.594472  14.594472  14.594472  14.594472  14.594472  24.488165
 [37]  24.488165  24.488165  24.488165  24.488165  24.488165  24.488165
 [43]  24.488165  24.488165  24.488165  24.488165  35.310242  35.310242
 [49]  35.310242  35.310242  35.310242  35.310242  35.310242  35.310242
 [55]  35.310242  35.310242  35.310242  46.899822  46.899822  46.899822
 [61]  46.899822  46.899822  46.899822  46.899822  46.899822  46.899822
 [67]  46.899822  46.899822  59.138400  59.138400  59.138400  59.138400
 [73]  59.138400  59.138400  59.138400  59.138400  59.138400  59.138400
 [79]  59.138400  69.699596  69.699596  69.699596  69.699596  69.699596
 [85]  69.699596  69.699596  69.699596  69.699596  69.699596  69.699596
 [91]  80.521673  80.521673  80.521673  80.521673  80.521673  80.521673
 [97]  80.521673  80.521673  80.521673  80.521673

$hat_lik_uni
           [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
[1,]  -6.907755    0    0    0    0    0    0    0    0     0     0     0     0
[2,] -13.815511    0    0    0    0    0    0    0    0     0     0     0     0
        [,14]    [,15]    [,16]    [,17]    [,18]    [,19]    [,20]    [,21]
[1,] 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165
[2,] 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165 2.903165
        [,22]    [,23]    [,24]    [,25]    [,26]    [,27]    [,28]    [,29]
[1,] 2.903165 2.903165 2.903165 7.297236 7.297236 7.297236 7.297236 7.297236
[2,] 2.903165 2.903165 2.903165 7.297236 7.297236 7.297236 7.297236 7.297236
        [,30]    [,31]    [,32]    [,33]    [,34]    [,35]    [,36]    [,37]
[1,] 7.297236 7.297236 7.297236 7.297236 7.297236 7.297236 12.24408 12.24408
[2,] 7.297236 7.297236 7.297236 7.297236 7.297236 7.297236 12.24408 12.24408
        [,38]    [,39]    [,40]    [,41]    [,42]    [,43]    [,44]    [,45]
[1,] 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408
[2,] 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408 12.24408
        [,46]    [,47]    [,48]    [,49]    [,50]    [,51]    [,52]    [,53]
[1,] 12.24408 17.65512 17.65512 17.65512 17.65512 17.65512 17.65512 17.65512
[2,] 12.24408 17.65512 17.65512 17.65512 17.65512 17.65512 17.65512 17.65512
        [,54]    [,55]    [,56]    [,57]    [,58]    [,59]    [,60]    [,61]
[1,] 17.65512 17.65512 17.65512 17.65512 23.44991 23.44991 23.44991 23.44991
[2,] 17.65512 17.65512 17.65512 17.65512 23.44991 23.44991 23.44991 23.44991
        [,62]    [,63]    [,64]    [,65]    [,66]    [,67]    [,68]   [,69]
[1,] 23.44991 23.44991 23.44991 23.44991 23.44991 23.44991 23.44991 29.5692
[2,] 23.44991 23.44991 23.44991 23.44991 23.44991 23.44991 23.44991 29.5692
       [,70]   [,71]   [,72]   [,73]   [,74]   [,75]   [,76]   [,77]   [,78]
[1,] 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692
[2,] 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692 29.5692
       [,79]    [,80]    [,81]    [,82]    [,83]    [,84]    [,85]    [,86]
[1,] 29.5692 31.39592 31.39592 31.39592 31.39592 31.39592 31.39592 31.39592
[2,] 29.5692 38.30368 38.30368 38.30368 38.30368 38.30368 38.30368 38.30368
        [,87]    [,88]    [,89]    [,90]    [,91]    [,92]    [,93]    [,94]
[1,] 31.39592 31.39592 31.39592 31.39592 36.80696 36.80696 36.80696 36.80696
[2,] 38.30368 38.30368 38.30368 38.30368 43.71471 43.71471 43.71471 43.71471
        [,95]    [,96]    [,97]    [,98]    [,99]   [,100]
[1,] 36.80696 36.80696 36.80696 36.80696 36.80696 36.80696
[2,] 43.71471 43.71471 43.71471 43.71471 43.71471 43.71471